//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StackUnderflow.Common.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public int answer_id { get; set; }
        public int user_id { get; set; }
        public string content { get; set; }
        public Nullable<int> rating { get; set; }
        public byte[] created { get; set; }
        public int question_id { get; set; }
    
        public virtual User User { get; set; }
        public virtual Question Question { get; set; }
    }
}
