//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StackUnderflow.Common.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public int answer_id { get; set; }
        public int user_id { get; set; }
        public string content { get; set; }
        public Nullable<int> rating { get; set; }
        public byte[] created { get; set; }
        public int question_id { get; set; }
    
        public virtual User User { get; set; }
        public virtual Question Question { get; set; }
    }
}
